trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
 #- task: CmdLine@2
 #  inputs:
 #   script: MSbuild.exe $(Build.BinariesDirectory)/*.sln
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'

